services:
  app:
    image: subratade9ok/file-transfer-local:latest
    ports:
      - "7827:7827"
    volumes:
      - ./test/uploads:/app/uploads
    # env_file: .env
    environment:
      - PORT=7827
      - UPLOAD_DIR=./uploads
      - BROWSE_PIN=1234
      - SESSION_SECRET=supersecret
    network_mode: host
