services:
  app:
    build: .
    volumes:
      - ./test/uploads:/app/uploads
    ports:
      - "7827:7827"
    # env_file: .env
    environment:
      - PORT=7827
      - UPLOAD_DIR=./uploads/ddd
      - BROWSE_PIN=1234
      - SESSION_SECRET=supersecret

    network_mode: host